# DB info
COCKROACH_DB_DRIVER: postgres
COCKROACH_DB_URL: postgres://root@localhost:26257/layerg?sslmode=disable
COCKROACH_DB_NAME: layerg
API_KEY_HEADER_NAME: X-API-KEY
API_PORT: ":8085"
APP_ID: f3e3bf76-62dc-42a7-ad0d-ef9033bc13a5

REDIS_DB_URL: localhost:6379
REDIS_DB_PASSWORD:
REDIS_DB: 0
# Multi-chain configs
