version: '3.5'

services:

 crdb:
   image: cockroachdb/cockroach:v24.2.1
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure
   volumes:
     - "~/.data/crdb:/cockroach/cockroach-data"