version: "3.5"

services:
  crdb:
    image: cockroachdb/cockroach:v24.2.1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - ../data/crdb:/cockroach/cockroach-data

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - ../redis_data:/bitnami/redis/data

  setup:
    image: u2labs/layerg-crawler:latest
    build:
      context: .
    depends_on:
      - crdb
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        make prepare &&
        make system-migrate-up &&
        make generated-migrate-up
      "

  server:
    image: u2labs/layerg-crawler:latest
    build:
      context: .
    depends_on:
      - setup
      - crdb
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: make all
    ports:
      - "${SERVICE_PORT:-8084}:8084"

  query:
    image: u2labs/layerg-crawler:latest
    build:
      context: .
    depends_on:
      - setup
      - crdb
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: make query
