version: "3.5"

services:
  crdb:
    image: cockroachdb/cockroach:v24.2.1
    container_name: crawler-db
    ports:
      - "26257:26257"
      - "8080:8080"
    command: "start-single-node --insecure  && cockroach sql --execute='CREATE DATABASE IF NOT EXISTS layerg;'"
    environment:
      - COCKROACH_DATABASE=layerg
    volumes:
      - ../data/crdb:/cockroach/cockroach-data

  redis:
    image: bitnami/redis:latest
    container_name: crawler-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - ../redis_data:/bitnami/redis/data

  app:
    image: u2labs/layerg-crawler:latest
    container_name: crawler-app
    command: --config layerg-crawler.yaml
    volumes:
      - ./layerg-crawler.yaml:/go/bin/layerg-crawler.yaml
      - ./subgraph.yaml:/go/bin/subgraph.yaml
    depends_on:
      - crdb
      - redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 300m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  query:
    image: u2labs/layerg-crawler:latest
    build:
      context: .
    container_name: crawler-query
    command: query --config layerg-crawler.yaml
    volumes:
      - ./layerg-crawler.yaml:/go/bin/layerg-crawler.yaml
      - ./schema.graphql:/go/bin/schema.graphql
    depends_on:
      - crdb
      - redis
    ports:
      - "8084:8084"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 300m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
