// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: erc_20_asset.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const add20Asset = `-- name: Add20Asset :exec
INSERT INTO
    erc_20_collection_assets (asset_id, owner, balance)
VALUES (
    $1, $2, $3
) RETURNING id, chain_id, asset_id, owner, balance, created_at, updated_at
`

type Add20AssetParams struct {
	AssetID string
	Owner   string
	Balance string
}

func (q *Queries) Add20Asset(ctx context.Context, arg Add20AssetParams) error {
	_, err := q.db.ExecContext(ctx, add20Asset, arg.AssetID, arg.Owner, arg.Balance)
	return err
}

const delete20Asset = `-- name: Delete20Asset :exec
DELETE 
FROM erc_20_collection_assets
WHERE
    id = $1
`

func (q *Queries) Delete20Asset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete20Asset, id)
	return err
}

const get20AssetByAssetId = `-- name: Get20AssetByAssetId :many
SELECT id, chain_id, asset_id, owner, balance, created_at, updated_at FROM erc_20_collection_assets WHERE asset_id = $1
`

func (q *Queries) Get20AssetByAssetId(ctx context.Context, assetID string) ([]Erc20CollectionAsset, error) {
	rows, err := q.db.QueryContext(ctx, get20AssetByAssetId, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Erc20CollectionAsset
	for rows.Next() {
		var i Erc20CollectionAsset
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.AssetID,
			&i.Owner,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get20AssetByAssetIdAndTokenId = `-- name: Get20AssetByAssetIdAndTokenId :one
SELECT id, chain_id, asset_id, owner, balance, created_at, updated_at FROM erc_20_collection_assets
WHERE
    asset_id = $1
    AND owner = $2
`

type Get20AssetByAssetIdAndTokenIdParams struct {
	AssetID string
	Owner   string
}

func (q *Queries) Get20AssetByAssetIdAndTokenId(ctx context.Context, arg Get20AssetByAssetIdAndTokenIdParams) (Erc20CollectionAsset, error) {
	row := q.db.QueryRowContext(ctx, get20AssetByAssetIdAndTokenId, arg.AssetID, arg.Owner)
	var i Erc20CollectionAsset
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.AssetID,
		&i.Owner,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const get20AssetByOwner = `-- name: Get20AssetByOwner :many
SELECT id, chain_id, asset_id, owner, balance, created_at, updated_at FROM erc_20_collection_assets
WHERE
    owner = $1
`

func (q *Queries) Get20AssetByOwner(ctx context.Context, owner string) ([]Erc20CollectionAsset, error) {
	rows, err := q.db.QueryContext(ctx, get20AssetByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Erc20CollectionAsset
	for rows.Next() {
		var i Erc20CollectionAsset
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.AssetID,
			&i.Owner,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update20Asset = `-- name: Update20Asset :exec
UPDATE erc_20_collection_assets
SET
    owner = $2 
WHERE 
    id = $1
`

type Update20AssetParams struct {
	ID    uuid.UUID
	Owner string
}

func (q *Queries) Update20Asset(ctx context.Context, arg Update20AssetParams) error {
	_, err := q.db.ExecContext(ctx, update20Asset, arg.ID, arg.Owner)
	return err
}
