// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: onchain_history.sql

package db

import (
	"context"
	"time"
)

const addOnchainTransaction = `-- name: AddOnchainTransaction :exec
INSERT INTO 
    onchain_histories("from","to",asset_id,token_id,amount,tx_hash,timestamp)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, "from", "to", asset_id, token_id, amount, tx_hash, timestamp, created_at, updated_at
`

type AddOnchainTransactionParams struct {
	From      string    `json:"from"`
	To        string    `json:"to"`
	AssetID   string    `json:"assetId"`
	TokenID   string    `json:"tokenId"`
	Amount    float64   `json:"amount"`
	TxHash    string    `json:"txHash"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) AddOnchainTransaction(ctx context.Context, arg AddOnchainTransactionParams) error {
	_, err := q.db.ExecContext(ctx, addOnchainTransaction,
		arg.From,
		arg.To,
		arg.AssetID,
		arg.TokenID,
		arg.Amount,
		arg.TxHash,
		arg.Timestamp,
	)
	return err
}
