// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tracking_contract.sql

package db

import (
	"context"
)

const getAllTrackingContractOnChain = `-- name: GetAllTrackingContractOnChain :many
SELECT chain_id, contract_address FROM tracking_contracts WHERE chain_id = $1
`

func (q *Queries) GetAllTrackingContractOnChain(ctx context.Context, chainID int32) ([]TrackingContract, error) {
	rows, err := q.db.QueryContext(ctx, getAllTrackingContractOnChain, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingContract
	for rows.Next() {
		var i TrackingContract
		if err := rows.Scan(&i.ChainID, &i.ContractAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
