// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package graphqldb

import (
	"time"
)

type Value struct {
	ID        string    `json:"id"`
	Value     string    `json:"value"`
	Sender    string    `json:"sender"`
	CreatedAt time.Time `json:"created_at"`
}
