// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package graphqldb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (Userprofile, error)
	GetCollectionByAddress(ctx context.Context, address string) (Collection, error)
	GetPostsByAuthor(ctx context.Context, author sql.NullString) ([]Post, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
}

var _ Querier = (*Queries)(nil)
