// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package graphqldb

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateMetadataUpdateRecord(ctx context.Context, arg CreateMetadataUpdateRecordParams) (MetadataUpdateRecord, error)
	CreateUser(ctx context.Context, id string) (User, error)
	DeleteItem(ctx context.Context, id string) error
	DeleteMetadataUpdateRecord(ctx context.Context, id string) error
	GetItem(ctx context.Context, id string) (Item, error)
	GetMetadataUpdateRecord(ctx context.Context, id string) (MetadataUpdateRecord, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListItem(ctx context.Context) ([]Item, error)
	ListMetadataUpdateRecord(ctx context.Context) ([]MetadataUpdateRecord, error)
	ListUser(ctx context.Context) ([]User, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateMetadataUpdateRecord(ctx context.Context, arg UpdateMetadataUpdateRecordParams) (MetadataUpdateRecord, error)
	// Skip update query generation as there are no updateable fields
	UpdateUser(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
