// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package graphqldb

import (
	"context"
)

const createBalance = `-- name: CreateBalance :one
INSERT INTO "balance" ("id", "item_id", "owner_id", "value", "updated_at", "contract") VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, item_id, owner_id, value, updated_at, contract, created_at
`

type CreateBalanceParams struct {
	ID        string `json:"id"`
	ItemID    string `json:"item_id"`
	OwnerID   string `json:"owner_id"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
	Contract  string `json:"contract"`
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, createBalance,
		arg.ID,
		arg.ItemID,
		arg.OwnerID,
		arg.Value,
		arg.UpdatedAt,
		arg.Contract,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.OwnerID,
		&i.Value,
		&i.UpdatedAt,
		&i.Contract,
		&i.CreatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO "item" ("id", "token_id", "token_uri", "standard") VALUES ($1, $2, $3, $4) RETURNING id, token_id, token_uri, standard, created_at
`

type CreateItemParams struct {
	ID       string `json:"id"`
	TokenID  string `json:"token_id"`
	TokenUri string `json:"token_uri"`
	Standard string `json:"standard"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ID,
		arg.TokenID,
		arg.TokenUri,
		arg.Standard,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.TokenUri,
		&i.Standard,
		&i.CreatedAt,
	)
	return i, err
}

const createMetadataUpdateRecord = `-- name: CreateMetadataUpdateRecord :one
INSERT INTO "metadata_update_record" ("id", "token_id", "actor_id", "timestamp") VALUES ($1, $2, $3, $4) RETURNING id, token_id, actor_id, timestamp, created_at
`

type CreateMetadataUpdateRecordParams struct {
	ID        string `json:"id"`
	TokenID   string `json:"token_id"`
	ActorID   string `json:"actor_id"`
	Timestamp string `json:"timestamp"`
}

func (q *Queries) CreateMetadataUpdateRecord(ctx context.Context, arg CreateMetadataUpdateRecordParams) (MetadataUpdateRecord, error) {
	row := q.db.QueryRowContext(ctx, createMetadataUpdateRecord,
		arg.ID,
		arg.TokenID,
		arg.ActorID,
		arg.Timestamp,
	)
	var i MetadataUpdateRecord
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ActorID,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" ("id") VALUES ($1) RETURNING id, created_at
`

func (q *Queries) CreateUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, id)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteBalance = `-- name: DeleteBalance :exec
DELETE FROM "balance" WHERE id = $1
`

func (q *Queries) DeleteBalance(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBalance, id)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM "item" WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const deleteMetadataUpdateRecord = `-- name: DeleteMetadataUpdateRecord :exec
DELETE FROM "metadata_update_record" WHERE id = $1
`

func (q *Queries) DeleteMetadataUpdateRecord(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMetadataUpdateRecord, id)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT id, item_id, owner_id, value, updated_at, contract, created_at FROM "balance" WHERE id = $1
`

func (q *Queries) GetBalance(ctx context.Context, id string) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getBalance, id)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.OwnerID,
		&i.Value,
		&i.UpdatedAt,
		&i.Contract,
		&i.CreatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, token_id, token_uri, standard, created_at FROM "item" WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.TokenUri,
		&i.Standard,
		&i.CreatedAt,
	)
	return i, err
}

const getMetadataUpdateRecord = `-- name: GetMetadataUpdateRecord :one
SELECT id, token_id, actor_id, timestamp, created_at FROM "metadata_update_record" WHERE id = $1
`

func (q *Queries) GetMetadataUpdateRecord(ctx context.Context, id string) (MetadataUpdateRecord, error) {
	row := q.db.QueryRowContext(ctx, getMetadataUpdateRecord, id)
	var i MetadataUpdateRecord
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ActorID,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at FROM "user" WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listBalance = `-- name: ListBalance :many
SELECT id, item_id, owner_id, value, updated_at, contract, created_at FROM "balance"
`

func (q *Queries) ListBalance(ctx context.Context) ([]Balance, error) {
	rows, err := q.db.QueryContext(ctx, listBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Balance{}
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.OwnerID,
			&i.Value,
			&i.UpdatedAt,
			&i.Contract,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItem = `-- name: ListItem :many
SELECT id, token_id, token_uri, standard, created_at FROM "item"
`

func (q *Queries) ListItem(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.TokenUri,
			&i.Standard,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadataUpdateRecord = `-- name: ListMetadataUpdateRecord :many
SELECT id, token_id, actor_id, timestamp, created_at FROM "metadata_update_record"
`

func (q *Queries) ListMetadataUpdateRecord(ctx context.Context) ([]MetadataUpdateRecord, error) {
	rows, err := q.db.QueryContext(ctx, listMetadataUpdateRecord)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataUpdateRecord{}
	for rows.Next() {
		var i MetadataUpdateRecord
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.ActorID,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUser = `-- name: ListUser :many
SELECT id, created_at FROM "user"
`

func (q *Queries) ListUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE "balance" SET "item_id" = $2, "owner_id" = $3, "value" = $4, "updated_at" = $5, "contract" = $6 WHERE id = $1 RETURNING id, item_id, owner_id, value, updated_at, contract, created_at
`

type UpdateBalanceParams struct {
	ID        string `json:"id"`
	ItemID    string `json:"item_id"`
	OwnerID   string `json:"owner_id"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
	Contract  string `json:"contract"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, updateBalance,
		arg.ID,
		arg.ItemID,
		arg.OwnerID,
		arg.Value,
		arg.UpdatedAt,
		arg.Contract,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.OwnerID,
		&i.Value,
		&i.UpdatedAt,
		&i.Contract,
		&i.CreatedAt,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE "item" SET "token_id" = $2, "token_uri" = $3, "standard" = $4 WHERE id = $1 RETURNING id, token_id, token_uri, standard, created_at
`

type UpdateItemParams struct {
	ID       string `json:"id"`
	TokenID  string `json:"token_id"`
	TokenUri string `json:"token_uri"`
	Standard string `json:"standard"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.ID,
		arg.TokenID,
		arg.TokenUri,
		arg.Standard,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.TokenUri,
		&i.Standard,
		&i.CreatedAt,
	)
	return i, err
}

const updateMetadataUpdateRecord = `-- name: UpdateMetadataUpdateRecord :one
UPDATE "metadata_update_record" SET "token_id" = $2, "actor_id" = $3, "timestamp" = $4 WHERE id = $1 RETURNING id, token_id, actor_id, timestamp, created_at
`

type UpdateMetadataUpdateRecordParams struct {
	ID        string `json:"id"`
	TokenID   string `json:"token_id"`
	ActorID   string `json:"actor_id"`
	Timestamp string `json:"timestamp"`
}

func (q *Queries) UpdateMetadataUpdateRecord(ctx context.Context, arg UpdateMetadataUpdateRecordParams) (MetadataUpdateRecord, error) {
	row := q.db.QueryRowContext(ctx, updateMetadataUpdateRecord,
		arg.ID,
		arg.TokenID,
		arg.ActorID,
		arg.Timestamp,
	)
	var i MetadataUpdateRecord
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ActorID,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec

DELETE FROM "user" WHERE id = $1
`

// Skip update query generation as there are no updateable fields
func (q *Queries) UpdateUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateUser, id)
	return err
}
