// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chain": {
            "get": {
                "description": "Get all supported chains",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chains"
                ],
                "summary": "Get all supported chains",
                "responses": {}
            },
            "post": {
                "description": "Add a new chain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chains"
                ],
                "summary": "Add a new chain",
                "parameters": [
                    {
                        "description": "Chain network information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/db.AddChainParams"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/chain/:chainId/asset": {
            "get": {
                "description": "Get all asset collection of the chain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset"
                ],
                "summary": "Get all asset collection of the chain",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Add a new asset collection to the chain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset"
                ],
                "summary": "Add a new asset collection to the chain",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset collection information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.AddNewAssetParamsSwagger"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "db.AddChainParams": {
            "type": "object",
            "properties": {
                "blockTime": {
                    "type": "integer"
                },
                "chain": {
                    "type": "string"
                },
                "chainID": {
                    "type": "integer"
                },
                "explorer": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latestBlock": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "rpcUrl": {
                    "type": "string"
                }
            }
        },
        "db.AssetType": {
            "type": "string",
            "enum": [
                "ERC721",
                "ERC1155",
                "ERC20"
            ],
            "x-enum-varnames": [
                "AssetTypeERC721",
                "AssetTypeERC1155",
                "AssetTypeERC20"
            ]
        },
        "utils.AddNewAssetParamsSwagger": {
            "type": "object",
            "properties": {
                "chainID": {
                    "type": "integer"
                },
                "collectionAddress": {
                    "type": "string"
                },
                "decimalData": {
                    "type": "integer"
                },
                "initialBlock": {
                    "type": "integer"
                },
                "lastUpdated": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/db.AssetType"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8085",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Swagger Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
